PL/Controllers/VentaProductoController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class VentaProductoController : Controller
    {
        private readonly IConfiguration _configuration;

        private readonly Microsoft.AspNetCore.Hosting.IHostingEnvironment _hostingEnvironment;

        public VentaProductoController(IConfiguration configuration, Microsoft.AspNetCore.Hosting.IHostingEnvironment hostingEnvironment)
        {
            _configuration = configuration;
            _hostingEnvironment = hostingEnvironment;
        }



        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Producto producto = new ML.Producto();
            ML.Result result = new ML.Result();
            producto.Proveedor = new ML.Proveedor();

            ML.Result resultproveedor = BL.Proveedor.GetAll();
            result = BL.Producto.GetAll(producto);


            if (result.Correct)
            {
                producto.Productos = result.Objects;
                producto.Proveedor.Proveedores = resultproveedor.Objects;
            }
            else
            {
                ViewBag.Message = "Error al hacer la consulta :";
            }
            return View(producto);

        }

        [HttpPost]
        public ActionResult GetAll(ML.Producto producto)
        {
            ML.Result result = new ML.Result();

            ML.Result resultproveedor = BL.Proveedor.GetAll();

            result = BL.Producto.GetAll(producto);

            //ML.Producto producto = new ML.Producto();

            if (result.Correct)
            {
                producto.Productos = result.Objects;
                producto.Proveedor.Proveedores = resultproveedor.Objects;
            }
            else
            {
                ViewBag.Message = "Error al hacer la consulta :";
            }
            return View(producto);

        }


        [HttpGet]
        public ActionResult CardPost(ML.Producto producto)
        {
            ML.VentaProducto ventaProducto = new ML.VentaProducto();
            ventaProducto.VentasProductos = new List<object>();

            if (HttpContext.Session.GetString("Producto") == null)
            {
                producto.Cantidad = producto.Cantidad = 1;
                producto.Total = producto.Total = (int)(producto.Cantidad * producto.PrecioUnitario);

                ventaProducto.VentasProductos.Add(producto);
                HttpContext.Session.SetString("Producto", Newtonsoft.Json.JsonConvert.SerializeObject(ventaProducto.VentasProductos));
                var session = HttpContext.Session.GetString("Producto");
            }
            else
            {
                var ventaSession = Newtonsoft.Json.JsonConvert.DeserializeObject<List<object>>(HttpContext.Session.GetString("Producto"));

                foreach (var obj in ventaSession)
                {
                    ML.Producto objProducto = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Producto>(obj.ToString());
                    ventaProducto.VentasProductos.Add(objProducto);
                }

                foreach (ML.Producto venta in ventaProducto.VentasProductos.ToList())
                {
                    if (producto.IdProducto == venta.IdProducto)
                    {
                        venta.Cantidad = venta.Cantidad + 1;
                    }
                    else
                    {
                        producto.Cantidad = producto.Cantidad = 1;
                        ventaProducto.VentasProductos.Add(producto);
                    }
                }
                HttpContext.Session.SetString("Producto", Newtonsoft.Json.JsonConvert.SerializeObject(ventaProducto.VentasProductos));
            }
            if (HttpContext.Session.GetString("Producto") != null)
            {
                ViewBag.Message = "Se ha agregado el producto al carrito";
                return View(producto);
            }
            else
            {
                ViewBag.Message = "No se pudo agregar el producto ):";
                return View(producto);
            }

        }

        [HttpGet]
        public ActionResult ResumenCompra(ML.VentaProducto ventaProducto)
        {
            if (HttpContext.Session.GetString("Producto") == null)
            {
                return View();
            }
            else
            {
                var ventaSession = Newtonsoft.Json.JsonConvert.DeserializeObject<List<object>>(HttpContext.Session.GetString("Producto"));
                ventaProducto.VentasProductos = new List<object>();

                foreach (var obj in ventaSession)
                {
                    ML.Producto objProducto = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Producto>(obj.ToString());
                    ventaProducto.VentasProductos.Add(objProducto);
                }

            }

            return View(ventaProducto);
        }





    }
}

PL/Views/VentaProducto/CardPost.cshtml
@{
    ViewData["Title"] = "CardPost";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>CardPost</h1>

@foreach (ML.Producto producto in Model.Productos)
{
    <tr>
        <td style="display :none;">@producto.IdProducto </td>
        @if (producto.Imagen != null)
        {
            <td style="text-align: center; vertical-align: middle;"><img src="data:image/*;base64,@producto.Imagen" style=" height:100px; width:100px; "></td>
        }
        else
        {
            <td style="text-align: center; vertical-align: middle;"><img src="~/Imagen/sinproducto.png" style=" height:100px; width:100px;"></td>
        }

        <td style="text-align: center; vertical-align: middle;">@producto.Nombre (@producto.Descripcion)</td>
        <td style="text-align: center; vertical-align: middle;">$@producto.PrecioUnitario</td>
        <td style="text-align: center; vertical-align: middle;">@producto.Stock</td>
        <td style="text-align: center; vertical-align: middle;"><a class="btn btn-success " href="@Url.Action("CardPost", "Producto", new { IdProducto = producto.IdProducto})"><i class="bi bi-plus-circle-fill" style="color: mintcream"></i></a></td>
        <td style="text-align: center; vertical-align: middle;">@producto.Cantidad</td>
        <td style="text-align: center; vertical-align: middle;"><a class="btn btn-success " href="@Url.Action("Delete", "Producto", new { IdProducto = producto.IdProducto})"><i class="bi bi-dash" style="color: mintcream"></i></a></td>
        <td style="text-align: center; vertical-align: middle;"><a class="btn btn-danger" href="@Url.Action("Delete", "Producto", new { IdProducto = producto.IdProducto})" onclick="return confirm('Estas seguro que deseas eliminar este producto?');"><i class="bi bi-x-square-fill" style="color: mintcream"></i></a></td>
   </tr>

   <tr>
                        
        <td></td>
        <td>Total:</td>
        <td>$@producto.Total</td>
   </tr>
}


                            
                           
                                
                            
                            

                            
                            

                        
                        
                    
               
                    

PL/Views/VentaProducto/GetAll.cshtml
@model ML.Producto
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>GetAll</h1>

@*@if (Context.Session.GetString("Producto") == null)
{
    <h2>El Carrito no tiene productos</h2>

    <div class="row">
        <div class="col-md-12">
            <h5>Regresa al catalogo para agregar productos al carrito</h5>
            <hr />
        </div>
        <div class="row">
            <div class="col-md-12">
                <div style="float:right">
                    @Html.ActionLink("Volver al catálogo", "GetAll", "VentaProducto", htmlAttributes: new { @class = "btn btn-success" })
                </div>
            </div>
        </div>
    </div>
}
else{
    <h2 class="text-center">Resumen de compra</h2>
    <hr/>

    <div class="row">
        <div class="col-md-12">
            <div style="float:right">
                @Html.ActionLink("Volver al catálogo", "GetAll", "VentaProducto", htmlAttributes: new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
    <br />*@

    <div class="row">
        <div class="table-responsive">
            <table class="table table-bordered table-responsive">
                <thead style="background-color: #aec1ff;font-family: arial;font-size: 1.2rem;">
                    <tr>
                        <td style="display :none;">id</td>
                        <td></td>
                        <td style="text-align: center;">Nombre</td>
                        <td style ="text-align: center;">Precio</td>
                        <td style="text-align: center;">Stock</td>}
                        <td style="text-align: center;">Descripción</td>
                        <td style="text-align: center; vertical-align: middle;">Agregar</td>
                        <td style="text-align: center; vertical-align: middle;">Cantidad</td>
                        <td style="text-align: center; vertical-align: middle;">Quitar</td>
                        <td style="text-align: center; vertical-align: middle;">Eliminar</td>
                    </tr>
                </thead>
                <tbody>
        </div>

                    <div class="row">

                        @foreach(ML.Producto producto in Model.Productos)
                        {
                            <div class="col mt-3 pt-3">
                                <div class="card text-Bold text @*text-white*@  bg-info border-dark border-top-0 mb-3 border-4" style="width: 15rem;">
                                    @if (producto.Imagen != null)
                                        { 
                                            <div class="text-center"> 
                                            <img src="data:image/*;base64,@producto.Imagen" class="img-thumbnail"  style="height:100%; width:50%;" />
                                            </div>
                                        }
                                         else
                                        { 
                                            <div class="text-center"> 
                                            <img src="~/Imagen/sinproducto.png" style="height:100%; width:50%;" /> 
                                            </div>
                                        } 
                                        <div class="card-body"> 
                                            <h5 class="card-title card-header text-center bg-light" id="pNombre">@producto.Nombre</h5>
                                            <p class="card-text" id="pPrecioUnitario">Precio Unitario:@producto.PrecioUnitario</p>
                                            <p class="card-text" id="pStock">Stock:@producto.Stock</p>
                                            @*<p class="card-text" id="pIdProveedor"></p>
                                            <p class="card-text" id="pDepartamento"></p>*@
                                            <p class="card-text" id="pDescripcion">Descripcion:@producto.Descripcion</p>


                                            @*@Html.ActionLink("Añadir", "CardPost", "VentaProducto", htmlAttributes: new { @class = "btn btn-secondary" })<i class="bi bi-cart3" style="color: darkorange"></i>*@

                                            @Html.ActionLink("Añadir", "CardPost", "VentaProducto", new { IdProducto = producto.IdProducto }, htmlAttributes: new { @class = "btn btn-secondary" })<i class="bi bi-cart3" style="color: darkorange"></i>

                                            @*<td style="text-align: center; vertical-align: middle;"><a class="btn btn-secondary" href="@Url.Action("Añadir", "CardPost", new { IdProducto = producto.IdProducto })" onclick=onclick="CrearObjeto();"><i class="bi bi-cart3" style="color: darkorange"></i>*@
                            
                                             @*<button class="btn btn-secondary" onclick="CrearObjeto()" >Añadir <i class="bi bi-cart3" style="color: darkorange"></i></button>       *@
                                        </div>
                                </div>
                            </div>
                        }
                    </div>
</div>

                    
}

PL/Views/VentaProducto/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("OK", "CardPost", "VentaProducto", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>