PL/Controllers/DepartamentoController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class DepartamentoController : Controller
    {
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Result result = BL.Departamento.GetAll();
            ML.Departamento departamento = new ML.Departamento();

            if (result.Correct)
            {
                departamento.Departamentos = result.Objects;
            }
            else
            {
                ViewBag.Message = "Error al hacer la consulta :";
            }
            return View(departamento);
        }

        [HttpGet]
        public ActionResult Form(int? IdDepartamento)
        {
            ML.Departamento departamento = new ML.Departamento();

            departamento.Area = new ML.Area();


            ML.Result resultArea = BL.Area.GetAll();

            if (IdDepartamento == null)
            {

                departamento.Area.Areas = resultArea.Objects;

                return View(departamento);
            }
            else
            {
                ML.Result result = BL.Departamento.DepartamentoGetByIdArea(IdDepartamento.Value);

                if (result.Correct)
                {
                    departamento = (ML.Departamento)result.Object;
                    departamento.Area.Areas = resultArea.Objects;
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al consultar el Usuario seleccionado";
                }
                return View(departamento);
            }

        }

        [HttpPost]

        public ActionResult Form(ML.Departamento departamento)
        {
            if (departamento.IdDepartamento == 0)
            {
                ML.Result result = BL.Departamento.Add(departamento);
                if (result.Correct)
                {
                    ViewBag.Message = "Se ha registrado el Departamento";
                    return PartialView("Modal");
                }
                else
                {
                    ViewBag.Message = "No se ha registrado el Departamento" + result.ErrorMessage;
                    return PartialView("Modal");
                }
            }
            else
            {
                ML.Result result = BL.Departamento.Update(departamento);
                if (result.Correct)
                {

                    ViewBag.Message = "Se ha Actualizado el Departamento";
                    return PartialView("Modal");
                }
                else
                {
                    ViewBag.Message = "No ha registrado el Departamento" + result.ErrorMessage;
                    return PartialView("Modal");
                }
            }

        }


        // DELETE

        [HttpGet]
        public ActionResult Delete(int IdDepartamento)
        {
            ML.Result result = new ML.Result();

            result = BL.Departamento.Delete(IdDepartamento);
            if (result.Correct)
            {
                ViewBag.Mensaje = "Se ha elimnado el registro";
                return PartialView("Modal");
            }
            else
            {
                ViewBag.Mensaje = "No see ha elimnado el registro" + result.ErrorMessage;
                return PartialView("Modal");
            }
        }
        public JsonResult GetDepartamento(int IdArea)
        {
            var result = BL.Departamento.DepartamentoGetByIdArea(IdArea);

            return Json(result.Objects);
        }
        //[HttpGet]
        //public ActionResult Form(int? IdDepartamento)
        //{
        //    ML.Departamento departamento = new ML.Departamento();
        //    departamento.Area = new ML.Area();

        //    ML.Result resultArea = BL.Area.GetAll();


        //    if (IdDepartamento == null)
        //    {
        //        //Lista de cascada de area
        //        departamento.Area.Areas = resultArea.Objects;

        //        return View(departamento);
        //    }
        //    else
        //    {
        //        //GetById
        //        ML.Result result = BL.Departamento.DepartamentoGetByIdArea(IdDepartamento.Value);

        //        if (result.Correct)
        //        {
        //            departamento = (ML.Departamento)result.Object;

        //            //Lista de cascada de paises
        //            departamento.Area.Areas = resultArea.Objects;
        //        }
        //        else
        //        {
        //            ViewBag.Message = "Error al consultar el producto seleccionado";
        //        }
        //        return View(departamento);
        //    }
        //}

        //[HttpPost]
        //public ActionResult Form(ML.Departamento departamento)
        //{

        //    if (departamento.IdDepartamento == 0)
        //    {
        //        //add Agregar
        //        ML.Result result = BL.Departamento.Add(departamento);

        //        if (result.Correct)
        //        {
        //            ViewBag.Message = "Se ha registrado el departamento";
        //            return PartialView("Modal");
        //        }
        //        else
        //        {
        //            ViewBag.Message = "Error al agregar el departamento" + result.ErrorMessage;
        //            return PartialView("Modal");
        //        }
        //    }
        //    else
        //    {
        //        //update Actualizar
        //        if (departamento != null)
        //        {
        //            ML.Result result = BL.Departamento.Update(departamento);
        //            if (result.Correct)
        //            {
        //                ViewBag.Message = "Se ha actualizado el departamento seleccionado";
        //                return PartialView("Modal");
        //            }
        //            else
        //            {
        //                ViewBag.Message = "Error al actualizar el departamento seleccionado";
        //                return PartialView("Modal");
        //            }
        //        }
        //    }
        //    return PartialView("Modal");
        //}


        // DELETE

        //[HttpGet]
        //public ActionResult Delete(ML.Departamento departamento)
        //{
        //    if (departamento != null)
        //    {
        //        ML.Result result = new ML.Result();
        //        result = BL.Departamento.Delete(departamento);
        //        if (result.Correct)
        //        {
        //            ViewBag.Message = "Se ha elimnado el registro correctamento";
        //            return PartialView("Modal");
        //        }
        //        else
        //        {
        //            ViewBag.Message = "Error no se elimino el registro" + result.ErrorMessage;
        //            return PartialView("Modal");
        //        }
        //    }
        //    else
        //    {
        //        return PartialView("Modal");
        //    }
        //}


        //public JsonResult GetDepartamento(int IdArea)
        //{
        //    var result = BL.Departamento.DepartamentoGetByIdArea(IdArea);

        //    return Json(result.Objects);
        //}


    }
}

PL/Views/Departamento/Form.cshtml
@model ML.Departamento
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <h2>Agregar Departamento</h2>
    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Departamento", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {

                <div class="form-group">
                    <div class="col-md-3">

                        @Html.LabelFor(model => model.Nombre)

                        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre" })

                        @Html.ValidationMessageFor(model => model.Nombre)

                    </div>
                </div>

                <div class="col-md-3">
                    <div class="form-group"></div>
                    @Html.LabelFor(model =>model.Area.IdArea)

                    @Html.DropDownListFor(model => model.Area.IdArea, new SelectList(Model.Area.Areas, "IdArea", "Nombre"), "Selecciona una opcion", new{id="ddlArea", @class = "form-control"})

                    @Html.ValidationMessageFor(model => model.Area.IdArea)
                </div>


                <div class="form-group">

                    <div class="col-md-3">

                        <input type="submit" value="Guardar" class="btn btn-success" />

                        @Html.ActionLink("Regresar", "GetAll", "Departamento", htmlAttributes: new { @class = "btn btn-danger" })

                    </div>

                </div>
            }
        </div>
    </div>
</div>

@section Scripts{

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#ddlArea").change(function () {
                $("#ddlDepartamento").empty();
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetDepartamento")',
                    dataType: 'json',
                    data: { IdArea: $("#ddlArea").val() },
                    success: function (departamentos) {
                        $("#ddlDepartamento").append('<option value="0">' + 'Seleccione una opción' + '</option>');
                        $.each(departamentos, function (i, departamentos) {
                            $("#ddlDepartamento").append('<option value="'
                                + departamentos.idDepartamento + '">'
                                + departamentos.nombre + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Failed.' + ex);
                    }
                });
            })
        })
    </script>
}

PL/Views/Departamento/GetAll.cshtml
@model ML.Departamento
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Departamentos</h2>

< class="container">

    <div class="row">
        <div style="float:right">
            @Html.ActionLink("Agregar", "Form", "Departamento", htmlAttributes: new { @class = "btn btn-success" })
        </div>
    </div>



    <div class="row">
        <table class="table table-responsive">
            <thead>
                <tr>
                    <th>Editar</th>

                    <th style="display:none">IdDepartamento</th>
                    <th>Departamento</th>
                    <th style="display:none">IdArea</th>
                    <th>Area</th>
                    <th>Eliminar</th>

                </tr>
            </thead>

            <tbody>
                @foreach(ML.Departamento departamento in Model.Departamentos){
                    <tr>
                        <td style="text-align: center; vertical-align: middle;"><a class="btn btn-warning" href="@Url.Action("Form", "Departamento", new { IdDepartamento = departamento.IdDepartamento})"><i class="bi bi-pencil-square" style="color: ivory"></i></a></td>
                        

                        <td style="display:none">@departamento.IdDepartamento</td>
                        <td>@departamento.Nombre</td>

                        <td style="display:none"> @departamento.Area.IdArea</td>
                        <td>@departamento.Area.Nombre</td>

                        
                        <td style="text-align: center; vertical-align: middle;"><a class="btn btn-danger" href="@Url.Action("Delete", "Departamento", new { IdDepartamento = departamento.IdDepartamento })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"><i class="bi bi-eraser-fill"></i></a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

PL/Views/Departamento/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("OK", "GetAll", "Departamento", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>